# 1 "data/maps/Sandbox_Gym/scripts.pory"

# 2 "data/maps/Sandbox_Gym/scripts.pory"
Sandbox_Gym_MapScripts::
# 3 "data/maps/Sandbox_Gym/scripts.pory"
	.byte 0
# 4 "data/maps/Sandbox_Gym/scripts.pory"

# 5 "data/maps/Sandbox_Gym/scripts.pory"
Sandbox_Gym_EventScript_Jeroen::
# 6 "data/maps/Sandbox_Gym/scripts.pory"
	trainerbattle_single TRAINER_JEROEN, Route102_Text_RickIntro, Route102_Text_RickDefeated
# 7 "data/maps/Sandbox_Gym/scripts.pory"
	msgbox Route102_Text_RickPostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/Sandbox_Gym/scripts.pory"
	end
# 9 "data/maps/Sandbox_Gym/scripts.pory"
	
# 10 "data/maps/Sandbox_Gym/scripts.pory"
Sandbox_Gym_EventScript_Rein::
# 11 "data/maps/Sandbox_Gym/scripts.pory"
	trainerbattle_single TRAINER_REIN, Route102_Text_RickIntro, Route102_Text_RickDefeated
# 12 "data/maps/Sandbox_Gym/scripts.pory"
	msgbox Route102_Text_RickPostBattle, MSGBOX_AUTOCLOSE
# 13 "data/maps/Sandbox_Gym/scripts.pory"
	end
