Islandview_ElderHouse_MapScripts::
	.byte 0


IslandviewTown_ElderHouse_ElderMan::
# 4 "data/maps/Islandview_ElderHouse/scripts.pory"
	msgbox IslandviewTown_ElderHouse_ElderMan_Text_0, MSGBOX_NPC
	end


IslandviewTown_ElderHouse_ElderWoman::
# 9 "data/maps/Islandview_ElderHouse/scripts.pory"
	msgbox IslandviewTown_ElderHouse_ElderWoman_Text_0, MSGBOX_NPC
	end


IslandviewTown_ElderHouse_ElderMan_Text_0:
# 4 "data/maps/Islandview_ElderHouse/scripts.pory"
	.string "This island used to be the initial\n"
	.string "outpost travellers used to travel to\l"
	.string "and from Mount Copan. Later on, they\l"
	.string "moved to the mainland. Life there is\l"
	.string "rowdy, I much prefer it here.$"

IslandviewTown_ElderHouse_ElderWoman_Text_0:
# 9 "data/maps/Islandview_ElderHouse/scripts.pory"
	.string "Around sunrise and sunset, between 6\n"
	.string "and 8 in the morning and at night, some\l"
	.string "Murkrow make a lot of noise around here.\l"
	.string "Very troubling.$"
