HarborTown_KidHouse_MapScripts::
	.byte 0


HarborTown_KidHouse_KidScript::
# 4 "data/maps/HarborTown_KidHouse/scripts.pory"
	lock
# 5 "data/maps/HarborTown_KidHouse/scripts.pory"
	faceplayer
# 6 "data/maps/HarborTown_KidHouse/scripts.pory"
	msgbox HarborTown_KidHouse_KidScript_Text_0
# 7 "data/maps/HarborTown_KidHouse/scripts.pory"
	release
	end


HarborTown_KidHouse_KidScript_Text_0:
# 6 "data/maps/HarborTown_KidHouse/scripts.pory"
	.string "I hear you can challenge the gyms on\n"
	.string "Mount Copan in whatever order you\l"
	.string "want! I want to challenge the\l"
	.string "Grass-type first, but my friend says he\l"
	.string "wants to challenge the Ice-type gym\l"
	.string "first. I guess we each will have to go\l"
	.string "our own way and meet at the top!$"
