IslandviewTown_MapScripts::
	.byte 0


IslandviewTown_EventScript_FatMan::
# 4 "data/maps/IslandviewTown/scripts.pory"
	msgbox IslandviewTown_EventScript_FatMan_Text_0, MSGBOX_NPC
	end


IslandviewTown_EventScript_NewGirl::
# 9 "data/maps/IslandviewTown/scripts.pory"
	msgbox IslandviewTown_EventScript_NewGirl_Text_0, MSGBOX_NPC
	end


IslandviewTown_EventScript_Bas::
# 14 "data/maps/IslandviewTown/scripts.pory"
	msgbox IslandviewTown_EventScript_Bas_Text_0, MSGBOX_NPC
	end


IslandviewTown_EventScript_FatMan_Text_0:
# 4 "data/maps/IslandviewTown/scripts.pory"
	.string "This island used to be the initial\n"
	.string "outpost travellers used to travel to\l"
	.string "and from Mount Copan. Later on, they\l"
	.string "moved to the mainland. Life there is\l"
	.string "rowdy, I much prefer it here.$"

IslandviewTown_EventScript_NewGirl_Text_0:
# 9 "data/maps/IslandviewTown/scripts.pory"
	.string "Hello this is a fun little test.$"

IslandviewTown_EventScript_Bas_Text_0:
# 14 "data/maps/IslandviewTown/scripts.pory"
	.string "Hallo ik ben Bas.$"
