IslandviewTown_MapScripts::
	.byte 0


IslandviewTown_EventScript_FatMan::
# 4 "data/maps/IslandviewTown/scripts.pory"
	msgbox IslandviewTown_EventScript_FatMan_Text_0, MSGBOX_NPC
	end


IslandviewTown_EventScript_FatMan_Text_0:
# 4 "data/maps/IslandviewTown/scripts.pory"
	.string "This island used to be the initial\n"
	.string "outpost travellers used to travel to\l"
	.string "and from Mount Copan. Later on, they\l"
	.string "moved to the mainland. Life there is\l"
	.string "rowdy, I much prefer it here.$"
