Islandview_LadyHouse_MapScripts::
	.byte 0


IslandviewTown_LadyHouse_FossilLady::
# 4 "data/maps/Islandview_LadyHouse/scripts.pory"
	msgbox IslandviewTown_LadyHouse_FossilLady_Text_0, MSGBOX_NPC
	end


IslandviewTown_LadyHouse_RivalMom::
# 9 "data/maps/Islandview_LadyHouse/scripts.pory"
	msgbox IslandviewTown_LadyHouse_RivalMom_Text_0, MSGBOX_NPC
	end


IslandviewTown_LadyHouse_FossilLady_Text_0:
# 4 "data/maps/Islandview_LadyHouse/scripts.pory"
	.string "Many years ago, STEEL E4 MEMBER\n"
	.string "settled here in search of rare and\l"
	.string "ancient pokemon and items. Little did\l"
	.string "he know his expedition would unlock\l"
	.string "such a goldrush. He moved out to live at\l"
	.string "sea, in private, but his son runs the Gym\l"
	.string "here. He's a colleague of my husband's,\l"
	.string "actually.$"

IslandviewTown_LadyHouse_RivalMom_Text_0:
# 9 "data/maps/Islandview_LadyHouse/scripts.pory"
	.string "Oh, PLAYER. RIVAL is so excited you two\n"
	.string "are finally allowed to become a trainer.\l"
	.string "Some youngsters already walk around\l"
	.string "with Pokemon, but I thought it better\l"
	.string "for him to first focus on his studies.\l"
	.string "Not that did much good... I hope you two\l"
	.string "look out for each other. You've known\l"
	.string "each other for so long after all.$"
