Harbor_Town_MapScripts::
	.byte 0


HarborTown_KidByHouseScript::
# 4 "data/maps/Harbor_Town/scripts.pory"
	lock
# 5 "data/maps/Harbor_Town/scripts.pory"
	faceplayer
# 6 "data/maps/Harbor_Town/scripts.pory"
	msgbox HarborTown_KidByHouseScript_Text_0
# 7 "data/maps/Harbor_Town/scripts.pory"
	release
	end


HarborTown_GuyByHousesScript::
# 12 "data/maps/Harbor_Town/scripts.pory"
	lock
# 13 "data/maps/Harbor_Town/scripts.pory"
	faceplayer
# 14 "data/maps/Harbor_Town/scripts.pory"
	msgbox HarborTown_GuyByHousesScript_Text_0
# 15 "data/maps/Harbor_Town/scripts.pory"
	release
	end


HarborTown_KidByCoastScript::
# 20 "data/maps/Harbor_Town/scripts.pory"
	lock
# 21 "data/maps/Harbor_Town/scripts.pory"
	faceplayer
# 22 "data/maps/Harbor_Town/scripts.pory"
	msgbox HarborTown_KidByCoastScript_Text_0
# 23 "data/maps/Harbor_Town/scripts.pory"
	release
	end


HarborTown_GuyAtDocks1Script::
# 28 "data/maps/Harbor_Town/scripts.pory"
	lock
# 29 "data/maps/Harbor_Town/scripts.pory"
	faceplayer
# 30 "data/maps/Harbor_Town/scripts.pory"
	msgbox HarborTown_GuyAtDocks1Script_Text_0
# 31 "data/maps/Harbor_Town/scripts.pory"
	release
	end


HarborTown_GuyAtDocks2Script::
# 36 "data/maps/Harbor_Town/scripts.pory"
	lock
# 37 "data/maps/Harbor_Town/scripts.pory"
	faceplayer
# 38 "data/maps/Harbor_Town/scripts.pory"
	msgbox HarborTown_GuyAtDocks2Script_Text_0
# 39 "data/maps/Harbor_Town/scripts.pory"
	release
	end


HarborTown_GuyAtDocks3Script::
# 44 "data/maps/Harbor_Town/scripts.pory"
	lock
# 45 "data/maps/Harbor_Town/scripts.pory"
	faceplayer
# 46 "data/maps/Harbor_Town/scripts.pory"
	msgbox HarborTown_GuyAtDocks3Script_Text_0
# 47 "data/maps/Harbor_Town/scripts.pory"
	release
	end


HarborTown_KidByHouseScript_Text_0:
# 6 "data/maps/Harbor_Town/scripts.pory"
	.string "Boats here travel from C to GOLDPORT and visit ports in between!\n\nEven though this region is small, it’s still so big! I want to visit all the places on the map! And those off the map too!$"

HarborTown_GuyByHousesScript_Text_0:
# 14 "data/maps/Harbor_Town/scripts.pory"
	.string "My uncle told me that this entire region is situated in a huge lake!\n\nThe Greater Copan Mountain, the surrounding area, even this body of water we call a “sea”! He says there is an exit somewhere…$"

HarborTown_KidByCoastScript_Text_0:
# 22 "data/maps/Harbor_Town/scripts.pory"
	.string "Something incredible happens here!\n\nRapidash gallop over the seas at very high speeds and Jumpluff float over the circular sea breeze from and toward the mountain!$"

HarborTown_GuyAtDocks1Script_Text_0:
# 30 "data/maps/Harbor_Town/scripts.pory"
	.string "These ships travel to BERRY COAST and GREENFINGER HARBOUR.\n\nTrade, travel, tourism; people find reasons to get around, don’t they?$"

HarborTown_GuyAtDocks2Script_Text_0:
# 38 "data/maps/Harbor_Town/scripts.pory"
	.string "Travellers that travel to BERRY COAST first, usually take a more leisurely route.\n\nThey tour up the shaded side of Copan, enjoy some succulent berries, enjoy the wine, and take in the views. A scenic trek along the Dors, perhaps.$"

HarborTown_GuyAtDocks3Script_Text_0:
# 46 "data/maps/Harbor_Town/scripts.pory"
	.string "Those who go to GREENFINGER HARBOUR first, take the hard but quick route.\n\nDefeat Gym Leaders, traverse dungeons and go against the river. Go against the height. Reach the top. Fight, climb, succeed!\n\nThat’s how we people and Pokemon should live! Sail towards GREENFINGER HARBOUR first, kid!$"
