Harbor_Town_MapScripts::
	.byte 0


HarborTown_KidByHouseScript::
# 4 "data/maps/Harbor_Town/scripts.pory"
	lock
# 5 "data/maps/Harbor_Town/scripts.pory"
	faceplayer
# 6 "data/maps/Harbor_Town/scripts.pory"
	msgbox HarborTown_KidByHouseScript_Text_0, MSGBOX_NPC
# 7 "data/maps/Harbor_Town/scripts.pory"
	release
	end


HarborTown_GuyByHousesScript::
# 12 "data/maps/Harbor_Town/scripts.pory"
	lock
# 13 "data/maps/Harbor_Town/scripts.pory"
	faceplayer
# 14 "data/maps/Harbor_Town/scripts.pory"
	msgbox HarborTown_GuyByHousesScript_Text_0, MSGBOX_NPC
# 15 "data/maps/Harbor_Town/scripts.pory"
	release
	end


HarborTown_KidByCoastScript::
# 20 "data/maps/Harbor_Town/scripts.pory"
	lock
# 21 "data/maps/Harbor_Town/scripts.pory"
	faceplayer
# 22 "data/maps/Harbor_Town/scripts.pory"
	msgbox HarborTown_KidByCoastScript_Text_0, MSGBOX_NPC
# 23 "data/maps/Harbor_Town/scripts.pory"
	release
	end


HarborTown_GuyAtDocks1Script::
# 28 "data/maps/Harbor_Town/scripts.pory"
	lock
# 29 "data/maps/Harbor_Town/scripts.pory"
	faceplayer
# 30 "data/maps/Harbor_Town/scripts.pory"
	msgbox HarborTown_GuyAtDocks1Script_Text_0, MSGBOX_NPC
# 31 "data/maps/Harbor_Town/scripts.pory"
	release
	end


HarborTown_GuyAtDocks2Script::
# 36 "data/maps/Harbor_Town/scripts.pory"
	lock
# 37 "data/maps/Harbor_Town/scripts.pory"
	faceplayer
# 38 "data/maps/Harbor_Town/scripts.pory"
	msgbox HarborTown_GuyAtDocks2Script_Text_0, MSGBOX_NPC
# 39 "data/maps/Harbor_Town/scripts.pory"
	release
	end


HarborTown_GuyAtDocks3Script::
# 44 "data/maps/Harbor_Town/scripts.pory"
	lock
# 45 "data/maps/Harbor_Town/scripts.pory"
	faceplayer
# 46 "data/maps/Harbor_Town/scripts.pory"
	msgbox HarborTown_GuyAtDocks3Script_Text_0, MSGBOX_NPC
# 47 "data/maps/Harbor_Town/scripts.pory"
	release
	end


HarborTown_KidByHouseScript_Text_0:
# 6 "data/maps/Harbor_Town/scripts.pory"
	.string "Boats here travel from C to GOLDPORT\n"
	.string "and visit ports in between! Even though\l"
	.string "this region is small, it’s still so big! I\l"
	.string "want to visit all the places on the map!\l"
	.string "And those off the map too!$"

HarborTown_GuyByHousesScript_Text_0:
# 14 "data/maps/Harbor_Town/scripts.pory"
	.string "My uncle told me that this entire region\n"
	.string "is situated in a huge lake! The Greater\l"
	.string "Copan Mountain, the surrounding area,\l"
	.string "even this body of water we call a “sea”!\l"
	.string "He says there is an exit somewhere…$"

HarborTown_KidByCoastScript_Text_0:
# 22 "data/maps/Harbor_Town/scripts.pory"
	.string "Something incredible happens here!\n"
	.string "Rapidash gallop over the seas at very\l"
	.string "high speeds and Jumpluff float over\l"
	.string "the circular sea breeze from and toward\l"
	.string "the mountain!$"

HarborTown_GuyAtDocks1Script_Text_0:
# 30 "data/maps/Harbor_Town/scripts.pory"
	.string "These ships travel to BERRY COAST and\n"
	.string "GREENFINGER HARBOUR. Trade, travel,\l"
	.string "tourism; people find reasons to get\l"
	.string "around, don’t they?$"

HarborTown_GuyAtDocks2Script_Text_0:
# 38 "data/maps/Harbor_Town/scripts.pory"
	.string "Travellers that travel to BERRY COAST\n"
	.string "first, usually take a more leisurely\l"
	.string "route. They tour up the shaded side of\l"
	.string "Copan, enjoy some succulent berries,\l"
	.string "enjoy the wine, and take in the views. A\l"
	.string "scenic trek along the Dors, perhaps.$"

HarborTown_GuyAtDocks3Script_Text_0:
# 46 "data/maps/Harbor_Town/scripts.pory"
	.string "Those who go to GREENFINGER HARBOUR\n"
	.string "first, take the hard but quick route.\n"
	.string "\n"
	.string "Defeat Gym Leaders, traverse dungeons\l"
	.string "and go against the river. Go against the\l"
	.string "height. Reach the top. Fight, climb,\l"
	.string "succeed!\n"
	.string "\n"
	.string "That’s how we people and Pokemon should\l"
	.string "live! Sail towards GREENFINGER HARBOUR\l"
	.string "first, kid!$"
