HarborTown_TwoDudesHouse_MapScripts::
	.byte 0


HarborTown_TwoDudesHouse_Dude1Script::
# 4 "data/maps/HarborTown_TwoDudesHouse/scripts.pory"
	lock
# 5 "data/maps/HarborTown_TwoDudesHouse/scripts.pory"
	faceplayer
# 6 "data/maps/HarborTown_TwoDudesHouse/scripts.pory"
	msgbox HarborTown_TwoDudesHouse_Dude1Script_Text_0, MSGBOX_NPC
# 7 "data/maps/HarborTown_TwoDudesHouse/scripts.pory"
	release
	end


HarborTown_TwoDudesHouse_Dude2Script::
# 12 "data/maps/HarborTown_TwoDudesHouse/scripts.pory"
	lock
# 13 "data/maps/HarborTown_TwoDudesHouse/scripts.pory"
	faceplayer
# 14 "data/maps/HarborTown_TwoDudesHouse/scripts.pory"
	msgbox HarborTown_TwoDudesHouse_Dude2Script_Text_0, MSGBOX_NPC
# 15 "data/maps/HarborTown_TwoDudesHouse/scripts.pory"
	release
	end


HarborTown_TwoDudesHouse_Dude1Script_Text_0:
# 6 "data/maps/HarborTown_TwoDudesHouse/scripts.pory"
	.string "There are four gym leaders on Mount\n"
	.string "Copan: THE SEDULOUS MAYOR, THE\l"
	.string "INTREPID TOXICOLOGIST, THE RUNAWAY\l"
	.string "TEMPLAR and THE SCION VOLCANOLOGIST.\l"
	.string "Though all gym leaders are capable\l"
	.string "fighters, they all have secondary\l"
	.string "ambitions around the mountain as well.\l"
	.string "Many come here from far away to\l"
	.string "challenge them or work with them.$"

HarborTown_TwoDudesHouse_Dude2Script_Text_0:
# 14 "data/maps/HarborTown_TwoDudesHouse/scripts.pory"
	.string "There are gym leaders in the area\n"
	.string "around Mount Copan. Our ISLANDVIEW of\l"
	.string "course houses THE ALOOF ARCHEOLOGIST.\l"
	.string "I don’t know where the others are. But if\l"
	.string "you’re serious about adventuring, you\l"
	.string "will find out on your own.$"
