HarborTown_TwoDudesHouse_MapScripts::
	.byte 0


HarborTown_TwoDudesHouse_Dude1Script::
# 4 "data/maps/HarborTown_TwoDudesHouse/scripts.pory"
	lock
# 5 "data/maps/HarborTown_TwoDudesHouse/scripts.pory"
	faceplayer
# 6 "data/maps/HarborTown_TwoDudesHouse/scripts.pory"
	msgbox HarborTown_TwoDudesHouse_Dude1Script_Text_0
# 7 "data/maps/HarborTown_TwoDudesHouse/scripts.pory"
	release
	end


HarborTown_TwoDudesHouse_Dude2Script::
# 12 "data/maps/HarborTown_TwoDudesHouse/scripts.pory"
	lock
# 13 "data/maps/HarborTown_TwoDudesHouse/scripts.pory"
	faceplayer
# 14 "data/maps/HarborTown_TwoDudesHouse/scripts.pory"
	msgbox HarborTown_TwoDudesHouse_Dude2Script_Text_0
# 15 "data/maps/HarborTown_TwoDudesHouse/scripts.pory"
	release
	end


HarborTown_TwoDudesHouse_Dude1Script_Text_0:
# 6 "data/maps/HarborTown_TwoDudesHouse/scripts.pory"
	.string "There are four gym leaders on Mount Copan: THE SEDULOUS MAYOR, THE INTREPID TOXICOLOGIST, THE RUNAWAY TEMPLAR and THE SCION VOLCANOLOGIST.\n\nThough all gym leaders are capable fighters, they all have secondary ambitions around the mountain as well. Many come here from far away to challenge them or work with them.$"

HarborTown_TwoDudesHouse_Dude2Script_Text_0:
# 14 "data/maps/HarborTown_TwoDudesHouse/scripts.pory"
	.string "There are gym leaders in the area around Mount Copan. Our ISLANDVIEW of course houses THE ALOOF ARCHEOLOGIST.\n\nI don’t know where the others are. But if you’re serious about adventuring, you will find out on your own.$"
