HarborTown_ElderlyLadyHouse_MapScripts::
	.byte 0


HarborTown_ElderlyLadyHouse_ElderlyLadyScript::
# 4 "data/maps/HarborTown_ElderlyLadyHouse/scripts.pory"
	lock
# 5 "data/maps/HarborTown_ElderlyLadyHouse/scripts.pory"
	faceplayer
# 6 "data/maps/HarborTown_ElderlyLadyHouse/scripts.pory"
	msgbox HarborTown_ElderlyLadyHouse_ElderlyLadyScript_Text_0
# 7 "data/maps/HarborTown_ElderlyLadyHouse/scripts.pory"
	release
	end


HarborTown_ElderlyLadyHouse_ElderlyLadyScript_Text_0:
# 6 "data/maps/HarborTown_ElderlyLadyHouse/scripts.pory"
	.string "There are many rare Pokemon around Mount Copan as well. If you look up, in the distance, you can see a thunderstorm, right? I bet a Pokemon is causing that. I know it’s off the beaten path but… after I rest up here, I’m gonna check it out. The terrain is inhospitable, but I just now defeated THE SCION VOLCANOLOGIST. I’m ready.$"
