HarborTown_ElderlyLadyHouse_MapScripts::
	.byte 0


HarborTown_ElderlyLadyHouse_ElderlyLadyScript::
# 4 "data/maps/HarborTown_ElderlyLadyHouse/scripts.pory"
	lock
# 5 "data/maps/HarborTown_ElderlyLadyHouse/scripts.pory"
	faceplayer
# 6 "data/maps/HarborTown_ElderlyLadyHouse/scripts.pory"
	msgbox HarborTown_ElderlyLadyHouse_ElderlyLadyScript_Text_0, MSGBOX_NPC
# 7 "data/maps/HarborTown_ElderlyLadyHouse/scripts.pory"
	release
	end


HarborTown_ElderlyLadyHouse_ElderlyLadyScript_Text_0:
# 6 "data/maps/HarborTown_ElderlyLadyHouse/scripts.pory"
	.string "There are many rare Pokemon around\n"
	.string "Mount Copan as well. If you look up, in\l"
	.string "the distance, you can see a\l"
	.string "thunderstorm, right? I bet a Pokemon is\l"
	.string "causing that. I know it’s off the beaten\l"
	.string "path but… after I rest up here, I’m\l"
	.string "gonna check it out. The terrain is\l"
	.string "inhospitable, but I just now defeated\l"
	.string "THE SCION VOLCANOLOGIST. I’m ready.$"
